/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Attendance = IDL.Record({
  'date' : IDL.Text,
  'recordId' : IDL.Nat,
  'labType' : IDL.Variant({
    'eod' : IDL.Null,
    'daysBrief' : IDL.Null,
    'attendance' : IDL.Null,
  }),
  'fiplCode' : IDL.Text,
  'reason' : IDL.Text,
  'daysOff' : IDL.Nat,
});
export const Employee = IDL.Record({
  'region' : IDL.Text,
  'status' : IDL.Variant({ 'active' : IDL.Null, 'onHold' : IDL.Null }),
  'joinDate' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'fseCategory' : IDL.Text,
  'department' : IDL.Text,
  'fiplCode' : IDL.Text,
});
export const FeedbackEntry = IDL.Record({
  'remark' : IDL.Text,
  'customerName' : IDL.Text,
  'contact' : IDL.Text,
  'agent' : IDL.Text,
  'callDate' : IDL.Text,
  'entryId' : IDL.Nat,
  'cesScore' : IDL.Float64,
  'brand' : IDL.Variant({
    'tineco' : IDL.Null,
    'ecovacs' : IDL.Null,
    'coway' : IDL.Null,
    'kuvings' : IDL.Null,
    'instant' : IDL.Null,
  }),
  'product' : IDL.Text,
  'fiplCode' : IDL.Text,
});
export const SalesRecord = IDL.Record({
  'saleType' : IDL.Variant({
    'accessories' : IDL.Null,
    'extendedWarranty' : IDL.Null,
  }),
  'recordId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'brand' : IDL.Variant({
    'tineco' : IDL.Null,
    'ecovacs' : IDL.Null,
    'coway' : IDL.Null,
    'kuvings' : IDL.Null,
    'instant' : IDL.Null,
  }),
  'amount' : IDL.Float64,
  'product' : IDL.Text,
  'saleDate' : IDL.Text,
  'fiplCode' : IDL.Text,
});
export const TopPerformer = IDL.Record({
  'accessories' : IDL.Nat,
  'name' : IDL.Text,
  'rank' : IDL.Nat,
  'totalSales' : IDL.Float64,
  'extendedWarranty' : IDL.Nat,
  'fiplCode' : IDL.Text,
});
export const Order = IDL.Variant({
  'less' : IDL.Null,
  'equal' : IDL.Null,
  'greater' : IDL.Null,
});
export const Performance = IDL.Record({
  'videoCallDemos' : IDL.Nat,
  'operationalDiscipline' : IDL.Float64,
  'softSkillsScore' : IDL.Float64,
  'productKnowledgeScore' : IDL.Float64,
  'salesInfluenceIndex' : IDL.Float64,
  'reviewCount' : IDL.Nat,
  'complaintVisits' : IDL.Nat,
  'demoVisits' : IDL.Nat,
  'fiplCode' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'totalSalesAmount' : IDL.Float64,
  'activeCount' : IDL.Nat,
  'averageCesScore' : IDL.Float64,
});
export const SWOT = IDL.Record({
  'weaknesses' : IDL.Vec(IDL.Text),
  'strengths' : IDL.Vec(IDL.Text),
  'threats' : IDL.Vec(IDL.Text),
  'opportunities' : IDL.Vec(IDL.Text),
  'cesScore' : IDL.Float64,
  'fiplCode' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAttendance' : IDL.Func(
      [Attendance],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addEmployee' : IDL.Func(
      [Employee],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addFeedback' : IDL.Func(
      [FeedbackEntry],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addSalesRecord' : IDL.Func(
      [SalesRecord],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'batchTopPerformersUpload' : IDL.Func(
      [IDL.Vec(TopPerformer)],
      [IDL.Record({ 'successCount' : IDL.Nat, 'failCount' : IDL.Nat })],
      [],
    ),
  'compareTopPerformersBySales' : IDL.Func(
      [TopPerformer, TopPerformer],
      [Order],
      ['query'],
    ),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'getActiveEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllPerformancesSortedBySII' : IDL.Func(
      [],
      [IDL.Vec(Performance)],
      ['query'],
    ),
  'getAttendanceByFIPL' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
  'getFeedbackByFIPL' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FeedbackEntry)],
      ['query'],
    ),
  'getPerformanceByFIPL' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Performance)],
      ['query'],
    ),
  'getSWOTByFIPL' : IDL.Func([IDL.Text], [IDL.Opt(SWOT)], ['query']),
  'getSalesByFIPL' : IDL.Func([IDL.Text], [IDL.Vec(SalesRecord)], ['query']),
  'getTopPerformers' : IDL.Func([], [IDL.Vec(TopPerformer)], ['query']),
  'updateEmployee' : IDL.Func([Employee], [], []),
  'upsertPerformance' : IDL.Func(
      [Performance],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'upsertSWOT' : IDL.Func(
      [SWOT],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Attendance = IDL.Record({
    'date' : IDL.Text,
    'recordId' : IDL.Nat,
    'labType' : IDL.Variant({
      'eod' : IDL.Null,
      'daysBrief' : IDL.Null,
      'attendance' : IDL.Null,
    }),
    'fiplCode' : IDL.Text,
    'reason' : IDL.Text,
    'daysOff' : IDL.Nat,
  });
  const Employee = IDL.Record({
    'region' : IDL.Text,
    'status' : IDL.Variant({ 'active' : IDL.Null, 'onHold' : IDL.Null }),
    'joinDate' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'fseCategory' : IDL.Text,
    'department' : IDL.Text,
    'fiplCode' : IDL.Text,
  });
  const FeedbackEntry = IDL.Record({
    'remark' : IDL.Text,
    'customerName' : IDL.Text,
    'contact' : IDL.Text,
    'agent' : IDL.Text,
    'callDate' : IDL.Text,
    'entryId' : IDL.Nat,
    'cesScore' : IDL.Float64,
    'brand' : IDL.Variant({
      'tineco' : IDL.Null,
      'ecovacs' : IDL.Null,
      'coway' : IDL.Null,
      'kuvings' : IDL.Null,
      'instant' : IDL.Null,
    }),
    'product' : IDL.Text,
    'fiplCode' : IDL.Text,
  });
  const SalesRecord = IDL.Record({
    'saleType' : IDL.Variant({
      'accessories' : IDL.Null,
      'extendedWarranty' : IDL.Null,
    }),
    'recordId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'brand' : IDL.Variant({
      'tineco' : IDL.Null,
      'ecovacs' : IDL.Null,
      'coway' : IDL.Null,
      'kuvings' : IDL.Null,
      'instant' : IDL.Null,
    }),
    'amount' : IDL.Float64,
    'product' : IDL.Text,
    'saleDate' : IDL.Text,
    'fiplCode' : IDL.Text,
  });
  const TopPerformer = IDL.Record({
    'accessories' : IDL.Nat,
    'name' : IDL.Text,
    'rank' : IDL.Nat,
    'totalSales' : IDL.Float64,
    'extendedWarranty' : IDL.Nat,
    'fiplCode' : IDL.Text,
  });
  const Order = IDL.Variant({
    'less' : IDL.Null,
    'equal' : IDL.Null,
    'greater' : IDL.Null,
  });
  const Performance = IDL.Record({
    'videoCallDemos' : IDL.Nat,
    'operationalDiscipline' : IDL.Float64,
    'softSkillsScore' : IDL.Float64,
    'productKnowledgeScore' : IDL.Float64,
    'salesInfluenceIndex' : IDL.Float64,
    'reviewCount' : IDL.Nat,
    'complaintVisits' : IDL.Nat,
    'demoVisits' : IDL.Nat,
    'fiplCode' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'totalSalesAmount' : IDL.Float64,
    'activeCount' : IDL.Nat,
    'averageCesScore' : IDL.Float64,
  });
  const SWOT = IDL.Record({
    'weaknesses' : IDL.Vec(IDL.Text),
    'strengths' : IDL.Vec(IDL.Text),
    'threats' : IDL.Vec(IDL.Text),
    'opportunities' : IDL.Vec(IDL.Text),
    'cesScore' : IDL.Float64,
    'fiplCode' : IDL.Text,
  });
  
  return IDL.Service({
    'addAttendance' : IDL.Func(
        [Attendance],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addEmployee' : IDL.Func(
        [Employee],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addFeedback' : IDL.Func(
        [FeedbackEntry],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addSalesRecord' : IDL.Func(
        [SalesRecord],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'batchTopPerformersUpload' : IDL.Func(
        [IDL.Vec(TopPerformer)],
        [IDL.Record({ 'successCount' : IDL.Nat, 'failCount' : IDL.Nat })],
        [],
      ),
    'compareTopPerformersBySales' : IDL.Func(
        [TopPerformer, TopPerformer],
        [Order],
        ['query'],
      ),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'getActiveEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllPerformancesSortedBySII' : IDL.Func(
        [],
        [IDL.Vec(Performance)],
        ['query'],
      ),
    'getAttendanceByFIPL' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
    'getFeedbackByFIPL' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FeedbackEntry)],
        ['query'],
      ),
    'getPerformanceByFIPL' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Performance)],
        ['query'],
      ),
    'getSWOTByFIPL' : IDL.Func([IDL.Text], [IDL.Opt(SWOT)], ['query']),
    'getSalesByFIPL' : IDL.Func([IDL.Text], [IDL.Vec(SalesRecord)], ['query']),
    'getTopPerformers' : IDL.Func([], [IDL.Vec(TopPerformer)], ['query']),
    'updateEmployee' : IDL.Func([Employee], [], []),
    'upsertPerformance' : IDL.Func(
        [Performance],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'upsertSWOT' : IDL.Func(
        [SWOT],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };