/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'date' : string,
  'recordId' : bigint,
  'labType' : { 'eod' : null } |
    { 'daysBrief' : null } |
    { 'attendance' : null },
  'fiplCode' : string,
  'reason' : string,
  'daysOff' : bigint,
}
export interface BatchResult {
  'errors' : Array<string>,
  'successCount' : bigint,
  'failCount' : bigint,
}
export interface DashboardStats {
  'totalEmployees' : bigint,
  'totalSalesAmount' : number,
  'activeCount' : bigint,
  'averageCesScore' : number,
}
export interface Employee {
  'region' : string,
  'status' : { 'active' : null } |
    { 'onHold' : null },
  'joinDate' : string,
  'name' : string,
  'role' : string,
  'fseCategory' : string,
  'avatarUrl' : string,
  'department' : string,
  'familyDetails' : string,
  'pastExperience' : string,
  'fiplCode' : string,
}
export interface FeedbackEntry {
  'remark' : string,
  'customerName' : string,
  'contact' : string,
  'agent' : string,
  'callDate' : string,
  'entryId' : bigint,
  'cesScore' : number,
  'brand' : { 'tineco' : null } |
    { 'ecovacs' : null } |
    { 'coway' : null } |
    { 'kuvings' : null } |
    { 'instant' : null },
  'product' : string,
  'fiplCode' : string,
}
export type Order = { 'less' : null } |
  { 'equal' : null } |
  { 'greater' : null };
export interface Performance {
  'videoCallDemos' : bigint,
  'operationalDiscipline' : number,
  'softSkillsScore' : number,
  'productKnowledgeScore' : number,
  'salesInfluenceIndex' : number,
  'reviewCount' : bigint,
  'complaintVisits' : bigint,
  'demoVisits' : bigint,
  'fiplCode' : string,
}
export interface SWOT {
  'weaknesses' : Array<string>,
  'strengths' : Array<string>,
  'traits' : Array<string>,
  'threats' : Array<string>,
  'opportunities' : Array<string>,
  'cesScore' : number,
  'problems' : Array<string>,
  'feedbacks' : Array<string>,
  'fiplCode' : string,
}
export interface SalesRecord {
  'saleType' : { 'accessories' : null } |
    { 'extendedWarranty' : null },
  'recordId' : bigint,
  'quantity' : bigint,
  'brand' : { 'tineco' : null } |
    { 'ecovacs' : null } |
    { 'coway' : null } |
    { 'kuvings' : null } |
    { 'instant' : null },
  'amount' : number,
  'product' : string,
  'saleDate' : string,
  'fiplCode' : string,
}
export interface TopPerformer {
  'accessories' : bigint,
  'name' : string,
  'rank' : bigint,
  'totalSales' : number,
  'extendedWarranty' : bigint,
  'fiplCode' : string,
}
export interface _SERVICE {
  'addAttendance' : ActorMethod<
    [Attendance],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addEmployee' : ActorMethod<[Employee], { 'ok' : null } | { 'err' : string }>,
  'addFeedback' : ActorMethod<
    [FeedbackEntry],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addSalesRecord' : ActorMethod<
    [SalesRecord],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'batchAttendanceUpload' : ActorMethod<[Array<Attendance>], BatchResult>,
  'batchEmployeeUpload' : ActorMethod<[Array<Employee>], BatchResult>,
  'batchFeedbackUpload' : ActorMethod<[Array<FeedbackEntry>], BatchResult>,
  'batchParametersUpload' : ActorMethod<[Array<Performance>], BatchResult>,
  'batchSWOTUpload' : ActorMethod<[Array<SWOT>], BatchResult>,
  'batchSalesUpload' : ActorMethod<[Array<SalesRecord>], BatchResult>,
  'batchTopPerformersUpload' : ActorMethod<[Array<TopPerformer>], BatchResult>,
  'compareTopPerformersBySales' : ActorMethod<
    [TopPerformer, TopPerformer],
    Order
  >,
  'deleteAllAttendance' : ActorMethod<[], undefined>,
  'deleteAllData' : ActorMethod<[], undefined>,
  'deleteAllEmployees' : ActorMethod<[], undefined>,
  'deleteAllFeedback' : ActorMethod<[], undefined>,
  'deleteAllPerformances' : ActorMethod<[], undefined>,
  'deleteAllSWOT' : ActorMethod<[], undefined>,
  'deleteAllSales' : ActorMethod<[], undefined>,
  'deleteAllTopPerformers' : ActorMethod<[], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'getActiveEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllPerformancesSortedBySII' : ActorMethod<[], Array<Performance>>,
  'getAttendanceByFIPL' : ActorMethod<[string], Array<Attendance>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getEmployee' : ActorMethod<[string], [] | [Employee]>,
  'getFeedbackByFIPL' : ActorMethod<[string], Array<FeedbackEntry>>,
  'getPerformanceByFIPL' : ActorMethod<[string], [] | [Performance]>,
  'getSWOTByFIPL' : ActorMethod<[string], [] | [SWOT]>,
  'getSalesByFIPL' : ActorMethod<[string], Array<SalesRecord>>,
  'getTopPerformers' : ActorMethod<[], Array<TopPerformer>>,
  'updateEmployee' : ActorMethod<[Employee], undefined>,
  'upsertPerformance' : ActorMethod<
    [Performance],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'upsertSWOT' : ActorMethod<[SWOT], { 'ok' : null } | { 'err' : string }>,
  /** Key-value store */
  'setKV' : ActorMethod<[string, string], undefined>,
  'getKV' : ActorMethod<[string], [] | [string]>,
  'getAllKV' : ActorMethod<[], Array<[string, string]>>,
  'deleteKV' : ActorMethod<[string], undefined>,
  'clearAllKV' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
